<?php

namespace Database\Seeders;

use App\Models\ReportSetting;
use Illuminate\Database\Seeder;

class ReportSettingSeeder extends Seeder
{
    public function run(): void
    {
        ReportSetting::insert([
            [
                'key' => 'receipt',
                'name' => 'Receipt',
                'naming_method' => 'prefix_year_sequence',
                'prefix' => 'REC',
                'current_sequence' => 1,
                'sequence_length' => 5,
                'reset_yearly' => true,
                'last_reset_year' => now()->year,
            ],
            [
                'key' => 'promissory_note',
                'name' => 'Promissory Note',
                'naming_method' => 'prefix_year_sequence',
                'prefix' => 'Pro',
                'current_sequence' => 1,
                'sequence_length' => 5,
                'reset_yearly' => true,
                'last_reset_year' => now()->year,
            ],
            [
                'key' => 'invoice',
                'name' => 'Invoice',
                'naming_method' => 'prefix_sequence',
                'prefix' => 'INV',
                'current_sequence' => 1,
                'sequence_length' => 5,
                'reset_yearly' => false,
                'last_reset_year' => null,
            ],
            [
                'key' => 'credit_note',
                'name' => 'Credit Note',
                'naming_method' => 'prefix_sequence',
                'prefix' => 'Cre',
                'current_sequence' => 1,
                'sequence_length' => 5,
                'reset_yearly' => false,
                'last_reset_year' => null,
            ],
            [
                'key' => 'dropcash_voucher',
                'name' => 'DropCash Voucher',
                'naming_method' => 'prefix_sequence',
                'prefix' => 'drop',
                'current_sequence' => 1,
                'sequence_length' => 5,
                'reset_yearly' => false,
                'last_reset_year' => null,
            ],
            [
                'key' => 'housekeeping_task',
                'name' => 'Housekeeping Task',
                'naming_method' => 'prefix_sequence',
                'prefix' => 'house',
                'current_sequence' => 1,
                'sequence_length' => 5,
                'reset_yearly' => false,
                'last_reset_year' => null,
            ],
            [
                'key' => 'guest_supplies_order',
                'name' => 'Guest Supplies Order',
                'naming_method' => 'prefix_sequence',
                'prefix' => 'Gue',
                'current_sequence' => 1,
                'sequence_length' => 5,
                'reset_yearly' => false,
                'last_reset_year' => null,
            ],
            [
                'key' => 'refund_voucher',
                'name' => 'Refund Voucher',
                'naming_method' => 'prefix_sequence',
                'prefix' => 'Ref',
                'current_sequence' => 1,
                'sequence_length' => 5,
                'reset_yearly' => false,
                'last_reset_year' => null,
            ],
            [
                'key' => 'security_deposit_refund_voucher',
                'name' => 'Security Deposit Refund Voucher',
                'naming_method' => 'prefix_sequence',
                'prefix' => 'Sec',
                'current_sequence' => 1,
                'sequence_length' => 5,
                'reset_yearly' => false,
                'last_reset_year' => null,
            ],
            [
                'key' => 'expenses_voucher',
                'name' => 'Expenses Voucher',
                'naming_method' => 'prefix_sequence',
                'prefix' => 'Exp',
                'current_sequence' => 1,
                'sequence_length' => 5,
                'reset_yearly' => false,
                'last_reset_year' => null,
            ],
            [
                'key' => 'deposit_voucher',
                'name' => 'Deposit Voucher',
                'naming_method' => 'prefix_sequence',
                'prefix' => 'Dep',
                'current_sequence' => 1,
                'sequence_length' => 5,
                'reset_yearly' => false,
                'last_reset_year' => null,
            ],
            [
                'key' => 'ota_product',
                'name' => 'OTA Product',
                'naming_method' => 'prefix_sequence',
                'prefix' => 'Ota',
                'current_sequence' => 1,
                'sequence_length' => 5,
                'reset_yearly' => false,
                'last_reset_year' => null,
            ],
            [
                'key' => 'inventory_order',
                'name' => 'Inventory Order',
                'naming_method' => 'prefix_sequence',
                'prefix' => 'Inv',
                'current_sequence' => 1,
                'sequence_length' => 5,
                'reset_yearly' => false,
                'last_reset_year' => null,
            ],
            [
                'key' => 'fund_transfer',
                'name' => 'Fund Transfer',
                'naming_method' => 'prefix_sequence',
                'prefix' => 'Fund',
                'current_sequence' => 1,
                'sequence_length' => 5,
                'reset_yearly' => false,
                'last_reset_year' => null,
            ],
            [
                'key' => 'orders',
                'name' => 'Orders',
                'naming_method' => 'prefix_sequence',
                'prefix' => 'Order',
                'current_sequence' => 1,
                'sequence_length' => 5,
                'reset_yearly' => false,
                'last_reset_year' => null,
            ],
        ]);
    }
}
